/**
 * Pillar 3: Intelligence — LLM reviews + schedule recommendation diff (task #10 wired).
 */
import React, { useCallback, useEffect, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";

import { acceptScheduleRecommendation, getInsight } from "../api/client";
import ScheduleDiff from "../components/ScheduleDiff";
import type { Insight, PeriodType } from "../types";

const PERIODS: PeriodType[] = ["weekly", "monthly"];

export default function Insights() {
  const [period, setPeriod] = useState<PeriodType>("weekly");
  const [insight, setInsight] = useState<Insight | null>(null);
  const [loading, setLoading] = useState(false);
  const [rejected, setRejected] = useState(false);

  // Reviews are generated by a Friday-noon / 1st-of-month reminder → manual
  // paste-into-Claude-Code step, never on demand — this screen only displays
  // whatever was last submitted for the selected period.
  const load = useCallback(async (p: PeriodType) => {
    setPeriod(p);
    setInsight(null);
    setRejected(false);
    setLoading(true);
    try {
      setInsight(await getInsight(p));
    } catch {
      // No insight generated yet for this period — empty state below handles it.
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(period); }, [load, period]);

  const handleAccept = async () => {
    await acceptScheduleRecommendation();
    setInsight((i) => (i ? { ...i, accepted: true } : i));
    Alert.alert("Schedule updated");
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.tabs}>
        {PERIODS.map((p) => (
          <Pressable
            key={p}
            style={[styles.tab, period === p && styles.tabActive]}
            onPress={() => load(p)}
          >
            <Text style={[styles.tabText, period === p && styles.tabTextActive]}>
              {p.charAt(0).toUpperCase() + p.slice(1)}
            </Text>
          </Pressable>
        ))}
      </View>

      {loading && <ActivityIndicator style={styles.loader} />}

      {insight && !loading && (
        <>
          <View style={styles.card}>
            <Text style={styles.cardLabel}>Narrative</Text>
            <Text style={styles.narrative}>{insight.narrative}</Text>
          </View>

          {insight.schedule_recommendation && !rejected && (
            <ScheduleDiff
              recommendation={insight.schedule_recommendation}
              accepted={insight.accepted}
              onAccept={handleAccept}
              onReject={() => setRejected(true)}
            />
          )}
        </>
      )}

      {!insight && !loading && (
        <Text style={styles.empty}>
          No {period} review yet — it's generated manually from the Friday-noon /
          1st-of-month reminder, not on demand.
        </Text>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container:     { flex: 1, backgroundColor: "#f5f5f5" },
  content:       { padding: 16, gap: 12 },
  tabs:          { flexDirection: "row", gap: 8, marginBottom: 4 },
  tab:           { flex: 1, paddingVertical: 8, alignItems: "center",
                   backgroundColor: "#e5e7eb", borderRadius: 8 },
  tabActive:     { backgroundColor: "#6366f1" },
  tabText:       { fontWeight: "600", color: "#374151" },
  tabTextActive: { color: "#fff" },
  loader:        { marginTop: 40 },
  card:          { backgroundColor: "#fff", padding: 16, borderRadius: 12 },
  cardLabel:     { fontSize: 12, fontWeight: "700", color: "#6366f1",
                   textTransform: "uppercase", marginBottom: 8 },
  narrative:     { fontSize: 15, lineHeight: 22, color: "#111" },
  empty:         { textAlign: "center", marginTop: 40, color: "#aaa", lineHeight: 20 },
});
