/** Read-only, data-driven narrative for the current Personal Insights review. */
import { useFocusEffect } from "@react-navigation/native";
import { LinearGradient } from "expo-linear-gradient";
import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { getCurrentInsights } from "../api/client";
import { ErrorState, Screen, SectionHeader } from "../components/ui";
import { colors } from "../theme";
import type { CurrentInsights } from "../types";
import { buildInsightStory, type StoryBeat, type StoryTone } from "../utils/insightStory";

const t = colors;
const tone: Record<StoryTone, { color: string; wash: string; marker: string }> = { positive: { color: t.success, wash: t.successSoft, marker: "↑" }, attention: { color: t.warning, wash: t.warningSoft, marker: "!" }, calm: { color: t.primary, wash: t.primarySoft, marker: "•" } };

function Evidence({ paths }: { paths: string[] }) {
  if (!paths.length) return null;
  return <View style={s.evidenceRow}>{paths.slice(0, 2).map((path) => <View key={path} style={s.evidence}><Text numberOfLines={1} style={s.evidenceText}>{path.split("/").pop()}</Text></View>)}</View>;
}

function Orbit({ tracked, partial, unknown, total }: { tracked: number; partial: number; unknown: number; total: number }) {
  const seen = total ? Math.round(((tracked + partial) / total) * 100) : 0;
  return <View style={s.orbitWrap}><View style={s.orbitOuter}><View style={s.orbitMiddle}><View style={s.orbitCore}><Text style={s.orbitValue}>{seen}%</Text><Text style={s.orbitLabel}>seen</Text></View></View></View><View style={[s.orbitDot, s.dotOne]} /><View style={[s.orbitDot, s.dotTwo]} /><Text style={s.coverageCaption}>{tracked} tracked · {partial} emerging · {unknown} unknown</Text></View>;
}

function Beat({ beat }: { beat: StoryBeat }) {
  const accent = tone[beat.tone];
  return <View style={[s.beat, { borderLeftColor: accent.color }]}><View style={s.beatHead}><Text style={[s.marker, { backgroundColor: accent.wash, color: accent.color }]}>{accent.marker}</Text><View style={s.grow}><Text style={[s.chapter, { color: accent.color }]}>{beat.chapter}</Text><Text style={s.beatTitle}>{beat.title}</Text></View></View><Text style={s.beatBody}>{beat.body}</Text><Text style={s.confidence}>{beat.confidence?.replaceAll("_", " ") ?? "reviewed"}</Text><Evidence paths={beat.evidence} /></View>;
}

function FutureLane({ label, items, color }: { label: string; items: string[]; color: string }) {
  if (!items.length) return null;
  return <View style={s.futureLane}><View style={[s.laneMark, { backgroundColor: color }]} /><View style={s.grow}><Text style={s.laneLabel}>{label}</Text>{items.map((item) => <Text key={item} style={s.laneItem}>• {item}</Text>)}</View></View>;
}

function Story({ insight }: { insight: CurrentInsights }) {
  const story = useMemo(() => buildInsightStory(insight), [insight]);
  const [pillarsOpen, setPillarsOpen] = useState(false);
  const [fullOpen, setFullOpen] = useState(false);
  const { routine_review: routine, future_plan_review: future, life_pillar_review: pillars } = insight.inference_bundle;
  return <>
    <LinearGradient colors={["#4949bd", "#7770dd", "#9a92f3"]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={s.hero}><View style={s.heroGlow} /><Text style={s.heroEyebrow}>YOUR REVIEW · {story.dateLabel.toUpperCase()}</Text><Text style={s.heroTitle}>A clearer view{"\n"}of your week.</Text><Text style={s.heroBody}>{story.opening}</Text><View style={s.heroPill}><Text style={s.heroPillText}>{story.goalCount} goals in focus</Text></View></LinearGradient>
    {insight.example && <View style={s.example}><Text style={s.exampleTitle}>Example review</Text><Text style={s.exampleText}>This is a structural preview, not personal analysis.</Text></View>}
    <View style={s.section}><SectionHeader eyebrow="THE WIDER PICTURE" title="What this review can see" /><View style={s.coverageCard}><Orbit {...story.coverage} /><View style={s.grow}><Text style={s.coverageTitle}>Pillar coverage</Text><Text style={s.coverageBody}>Evidence is shown as it exists. Topics without records stay unknown—not a setback.</Text></View></View></View>
    <View style={s.section}><SectionHeader eyebrow="THE STORY" title="Signals from this review" />{story.beats.length ? story.beats.map((beat) => <Beat key={beat.id} beat={beat} />) : <View style={s.placeholder}><Text style={s.placeholderTitle}>The story is still forming</Text><Text style={s.placeholderText}>No evidence-backed signals were saved in this review yet.</Text></View>}</View>
    <View style={s.section}><SectionHeader eyebrow="ROUTINE LENS" title={routine.summary} />{Object.entries(routine.metrics).map(([name, value]) => <View key={name} style={s.metric}><View style={s.metricDot} /><Text style={s.metricName}>{name.replaceAll("_", " ")}</Text><Text style={s.metricValue}>{String(value)}</Text></View>)}{!!routine.experiments.length && <View style={s.experiments}><Text style={s.promptLabel}>REVIEW PROMPTS</Text>{routine.experiments.map((item) => <Text key={item} style={s.prompt}>→ {item}</Text>)}</View>}</View>
    <View style={s.section}><SectionHeader eyebrow="FUTURE PLAN" title={future.summary} /><View style={s.futureBoard}><FutureLane label="Progress carried forward" color={t.success} items={future.progress_updates.map((item) => item.statement)} /><FutureLane label="New threads" color={t.primary} items={future.new_additions.map((item) => item.statement)} /><FutureLane label="Questions to resolve" color={t.warning} items={future.unresolved_questions} />{!future.progress_updates.length && !future.new_additions.length && !future.unresolved_questions.length && <Text style={s.emptyBoard}>No future-plan signals were saved in this review.</Text>}</View></View>
    {!!story.questions.length && <View style={s.questions}><Text style={s.questionEyebrow}>NEXT TIME</Text><Text style={s.questionTitle}>Questions worth carrying forward</Text>{story.questions.map((question) => <Text key={question} style={s.question}>• {question}</Text>)}</View>}
    <View style={s.section}><Pressable accessibilityRole="button" accessibilityLabel="Life-pillar map" accessibilityState={{ expanded: pillarsOpen }} onPress={() => setPillarsOpen(!pillarsOpen)} style={s.disclosure}><View><Text style={s.eyebrow}>DETAIL</Text><Text style={s.disclosureTitle}>Life-pillar map</Text></View><Text style={s.disclosureIcon}>{pillarsOpen ? "−" : "+"}</Text></Pressable>{pillarsOpen && <><Text style={s.pillarIntro}>{pillars.summary}</Text>{pillars.groups.map((group) => <View key={group.name} style={s.pillarGroup}><Text style={s.pillarName}>{group.name.replaceAll("_", " ")}</Text><View style={s.topicWrap}>{group.topics.map((topic) => <View key={topic.name} style={[s.topic, topic.status === "tracked" ? s.topicTracked : topic.status === "partially_tracked" ? s.topicPartial : s.topicUnknown]}><Text style={s.topicText}>{topic.name.replaceAll("_", " ")}</Text></View>)}</View></View>)}</>}</View>
    <Pressable accessibilityRole="button" accessibilityLabel={fullOpen ? "Hide full synthesis" : "Read full synthesis"} accessibilityState={{ expanded: fullOpen }} onPress={() => setFullOpen(!fullOpen)} style={s.footerToggle}><Text style={s.footerText}>{fullOpen ? "Hide full synthesis" : "Read full synthesis"}</Text><Text style={s.footerText}>{fullOpen ? "↑" : "↓"}</Text></Pressable>{fullOpen && <Text style={s.full}>{insight.narrative}</Text>}
  </>;
}

export default function Insights() {
  const [insight, setInsight] = useState<CurrentInsights | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setInsight(await getCurrentInsights()); } catch (cause) { setInsight(null); setError(String(cause)); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  if (loading) return <Screen style={s.state}><ActivityIndicator color={t.primary} /><Text style={s.stateText}>Reading your saved review…</Text></Screen>;
  if (error) return <Screen style={s.state}><ErrorState title="Your review is unavailable" body={`Could not load the current synthesis. ${error}`} /></Screen>;
  if (insight?.example) return <Screen style={s.state}><Text style={s.emptyTitle}>No personal review has been published</Text><Text style={s.emptyCopy}>The available artifact is only a structural example. It is never presented as your data.</Text></Screen>;
  return insight ? <Screen><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Story insight={insight} /></ScrollView></Screen> : null;
}

const s = StyleSheet.create({
  content: { padding: 16, paddingBottom: 40, gap: 24 }, state: { flex: 1, justifyContent: "center", alignItems: "center", padding: 32, gap: 12 }, stateText: { color: t.muted }, emptyTitle: { color: t.ink, fontSize: 18, fontWeight: "800", textAlign: "center" }, emptyCopy: { color: t.muted, fontSize: 14, lineHeight: 20, textAlign: "center", maxWidth: 300 },
  hero: { borderRadius: 24, padding: 24, minHeight: 270, overflow: "hidden", justifyContent: "flex-end", gap: 10 }, heroGlow: { position: "absolute", width: 180, height: 180, borderRadius: 90, backgroundColor: "rgba(255,255,255,0.15)", right: -46, top: -62 }, heroEyebrow: { color: "#dddafe", fontWeight: "800", fontSize: 10, letterSpacing: 1.2 }, heroTitle: { color: "#fff", fontSize: 31, lineHeight: 36, letterSpacing: -0.8, fontWeight: "800" }, heroBody: { color: "#f4f3ff", fontSize: 14, lineHeight: 20 }, heroPill: { alignSelf: "flex-start", backgroundColor: "rgba(255,255,255,0.18)", paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999 }, heroPillText: { color: "#fff", fontWeight: "700", fontSize: 12 },
  example: { borderRadius: 16, padding: 14, backgroundColor: t.warningSoft, borderWidth: 1, borderColor: t.border, gap: 3 }, exampleTitle: { fontWeight: "800", color: t.warning }, exampleText: { color: t.warningText, fontSize: 13 }, section: { gap: 12 }, eyebrow: { fontSize: 10, fontWeight: "800", color: t.muted, letterSpacing: 1.1 }, grow: { flex: 1 },
  coverageCard: { backgroundColor: t.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: t.border, flexDirection: "row", alignItems: "center", gap: 14 }, orbitWrap: { alignItems: "center", width: 120, gap: 6 }, orbitOuter: { width: 88, height: 88, borderRadius: 44, borderWidth: 8, borderColor: t.primarySoft, alignItems: "center", justifyContent: "center" }, orbitMiddle: { width: 62, height: 62, borderRadius: 31, backgroundColor: t.successSoft, alignItems: "center", justifyContent: "center" }, orbitCore: { width: 47, height: 47, borderRadius: 24, backgroundColor: t.surface, alignItems: "center", justifyContent: "center" }, orbitValue: { color: t.ink, fontWeight: "800", fontSize: 16 }, orbitLabel: { color: t.muted, fontSize: 9 }, orbitDot: { position: "absolute", width: 9, height: 9, borderRadius: 5 }, dotOne: { top: 9, right: 18, backgroundColor: t.primary }, dotTwo: { top: 37, left: 6, backgroundColor: t.success }, coverageCaption: { fontSize: 10, color: t.muted, textAlign: "center" }, coverageTitle: { fontWeight: "800", color: t.ink, fontSize: 15, marginBottom: 5 }, coverageBody: { color: t.muted, lineHeight: 18, fontSize: 12 },
  beat: { backgroundColor: t.surface, borderRadius: 16, padding: 15, borderWidth: 1, borderColor: t.border, borderLeftWidth: 4, gap: 9 }, beatHead: { flexDirection: "row", alignItems: "center", gap: 10 }, marker: { width: 28, height: 28, borderRadius: 14, textAlign: "center", textAlignVertical: "center", fontWeight: "900", fontSize: 16 }, chapter: { textTransform: "uppercase", fontSize: 10, letterSpacing: 1, fontWeight: "800" }, beatTitle: { color: t.ink, fontSize: 14, fontWeight: "800" }, beatBody: { color: t.ink, fontSize: 14, lineHeight: 20 }, confidence: { color: t.muted, fontSize: 11, textTransform: "capitalize" }, evidenceRow: { flexDirection: "row", gap: 5, flexWrap: "wrap" }, evidence: { maxWidth: "100%", backgroundColor: t.track, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 }, evidenceText: { color: t.muted, fontSize: 10, maxWidth: 190 },
  placeholder: { padding: 20, backgroundColor: t.surface, borderRadius: 18, borderWidth: 1, borderColor: t.border, gap: 5 }, placeholderTitle: { color: t.ink, fontWeight: "800" }, placeholderText: { color: t.muted, fontSize: 13, lineHeight: 19 }, metric: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderColor: t.border, gap: 8 }, metricDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: t.primary }, metricName: { flex: 1, color: t.muted, fontSize: 13, textTransform: "capitalize" }, metricValue: { color: t.ink, fontWeight: "800", fontSize: 14, fontVariant: ["tabular-nums"] }, experiments: { backgroundColor: t.primarySoft, padding: 14, borderRadius: 14, gap: 6 }, promptLabel: { color: t.primary, fontSize: 10, letterSpacing: 1, fontWeight: "800" }, prompt: { color: t.primaryText, fontSize: 13, lineHeight: 18 },
  futureBoard: { backgroundColor: t.surface, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: t.border, gap: 14 }, futureLane: { flexDirection: "row", gap: 10 }, laneMark: { width: 4, borderRadius: 4, alignSelf: "stretch" }, laneLabel: { color: t.ink, fontWeight: "800", fontSize: 13, marginBottom: 4 }, laneItem: { color: t.muted, fontSize: 13, lineHeight: 19, marginBottom: 2 }, emptyBoard: { color: t.muted, fontSize: 13, lineHeight: 19 }, questions: { backgroundColor: t.inverseSurface, borderRadius: 20, padding: 18, gap: 8 }, questionEyebrow: { color: t.inverseMuted, fontWeight: "800", fontSize: 10, letterSpacing: 1.1 }, questionTitle: { color: t.inverse, fontWeight: "800", fontSize: 19 }, question: { color: t.inverse, fontSize: 13, lineHeight: 19, opacity: 0.84 }, disclosure: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: t.surface, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: t.border }, disclosureTitle: { color: t.ink, fontWeight: "800", fontSize: 16, marginTop: 2 }, disclosureIcon: { color: t.primary, fontSize: 25 }, pillarIntro: { color: t.muted, lineHeight: 19, fontSize: 13 }, pillarGroup: { gap: 8 }, pillarName: { color: t.ink, fontWeight: "800", textTransform: "capitalize", fontSize: 14 }, topicWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, topic: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 }, topicTracked: { backgroundColor: t.successSoft }, topicPartial: { backgroundColor: t.primarySoft }, topicUnknown: { backgroundColor: t.track }, topicText: { color: t.ink, fontSize: 11, textTransform: "capitalize" }, footerToggle: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 4 }, footerText: { color: t.primary, fontWeight: "800", fontSize: 13 }, full: { color: t.muted, lineHeight: 20, fontSize: 13, paddingHorizontal: 4 },
});
